import { test, expect } from '@playwright/test';

//teste só pode ser realizado até o dia 23/08/2024.
test('test', async ({ page }) => {
  await page.goto('https://www.ryanair.com/pt/pt');
  await page.getByRole('button', { name: 'Sim, concordo' }).click();
  await page.getByPlaceholder('Partida').click();
  await page.getByRole('button', { name: 'Porto' }).click();
  await page.getByRole('button', { name: 'Itália' }).click();
  await page.getByRole('button', { name: 'Milão (Todos os aeroportos)' }).click();
  await page.getByText('ago.').first().click();
  await page.getByText('23').first().click();
  await page.getByText('25').nth(1).click();
  await page.getByLabel('Feito').click();
  await page.locator('ry-checkbox div').nth(1).click();
  await page.getByLabel('Pesquisar').click();
  await page.locator('flight-card-summary').filter({ hasText: 'Tarifa Basic 156,99 € 136,74' }).getByRole('button').click();
  await expect(page.getByText('Milão (Todos os aeroportos) para Porto Ordenar voos por 23ago. sexta-feira € 71')).toBeVisible();
  await page.getByRole('button', { name: '26ago. segunda-feira € 51 ,' }).click();
  await page.getByRole('button', { name: 'Selecionar' }).click();
  await page.getByRole('columnheader', { name: 'Image that represents standard fare Basic Viaja sem peso Continuar para € 187 ,' }).locator('div').nth(4).click();
  await page.getByRole('button', { name: 'Continuar com Basic' }).click();
  await page.getByRole('button', { name: 'Iniciar sessão mais tarde' }).click();
  await page.getByRole('button', { name: '-', exact: true }).click();
  await page.getByRole('button', { name: 'Sr.', exact: true }).click();
  await page.getByLabel('Nome próprio').click();
  await page.getByLabel('Nome próprio').fill('Pedro');
  await page.getByLabel('Apelido').click();
  await page.getByLabel('Apelido').fill('Cardoso');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.locator('bags-small-bag-pax-control label').click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'undefined Opção 2: Selecionar' }).click();
  await page.getByRole('button', { name: 'Continuar sem um lugar' }).click();
  await page.getByRole('button', { name: 'Continuar com a atribuição' }).click();
  await page.waitForTimeout(5000);
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await expect(page.frameLocator('#ry-modal-portal iframe').getByText('Início de sessão na contaContinuar com o GoogleContinuar com o')).toBeVisible();
});
